import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/UserContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book your services',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <UserProvider>
      {children}
      </UserProvider>
      </body>
    </html>
  )
}
