// RootLayout.js
import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/UserContext'
import ToastProvider from '@/components/Toast/ToastProvider';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book your services',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </UserProvider>
      </body>
    </html>
  )
}
